name: Auto Api Task

on:
  schedule:
    - cron: '12 */3 * * *'
  release:
    types: [published]
  push:
    branches: 
      - main
  watch:
    types: [started]
   
jobs:
   Task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests
      run: |
        pip install requests
    - name: Read config from secrets
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }}
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
      run: | 
        echo $CONFIG_ID > client.txt
        echo $CONFIG_KEY > secret.txt
    - name: Test Api
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python script.py
    - name: Delete secrets config
      run: | 
        rm -f client.txt
        rm -f secret.txt
    - name: Commit
      run: |
        git config --global user.email eexto@aol.com
        git config --global user.name not-eexto
        git add .
        git commit -m "update new refresh_token" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
